#define LIBPRESSIO_VERSION "0.86.2  lua distributed noop zfp sz3"
#define LIBPRESSIO_COMPRESSORS "noop zfp sz3"
#define LIBPRESSIO_FEATURES " lua distributednoop zfp sz3"
#define LIBPRESSIO_MAJOR_VERSION 0
#define LIBPRESSIO_MINOR_VERSION 86
#define LIBPRESSIO_PATCH_VERSION 2
#define LIBPRESSIO_HAS_SZ 0
#define LIBPRESSIO_HAS_ZFP 1
#define LIBPRESSIO_HAS_MGARD 0
#define LIBPRESSIO_HAS_MAGICK 0
#define LIBPRESSIO_HAS_BLOSC 0
#define LIBPRESSIO_HAS_FPZIP 0
#define LIBPRESSIO_HAS_MPI 0
#define LIBPRESSIO_HAS_MPI4PY 0
#define LIBPRESSIO_HAS_LUA 1
#define LIBPRESSIO_HAS_JSON 0

#define LIBPRESSIO_COMPAT_HAS_IMAGEMAGICK_LONGLONG 0
#define LIBPRESSIO_MGARD_NEED_FLOAT_HEADER 0
#define LIBPRESSIO_MGARD_HAS_CONFIG_HEADER 0
#define LIBPRESSIO_MGARD_HAS_CONFIG_HEADER_HPP 0
